apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-tp-1
    version: "1.0"
  name: devops-tp-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-tp-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devops-tp-1
    spec:
      containers:
        - name: devops-tp-1
          image: edric14/devops_tp_1:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devops-tp-1
  name: devops-tp-1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: devops-tp-1
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"


---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: carservice
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /devops-tp-1/
      rewrite:
        uri: /
      route:
        - destination:
            port:
              number: 80
            host: devops-tp-1.default.svc.cluster.local